print("Olá mundo")
print("Meu nome é Esther")
print("o dia esta ensolarado")
print("tenho 17 anos")
print("Amo a Ariana grande")
print("tenho um cachorro")
print("amo macarrão ")
print("adoro animais principalmente girafas ")
print("amo ir pra praia")
print("faço aniversario dia 29/09")